### ISSUE TITLE
トップページが読み込まれた後で、songs APIエンドポイントは繰り返し呼び出される

### ISSUE THREAD

**Issue by bma2takato** [cma2819/sdvx-copyright-checker#36]
ユーザーが何もしていなくても、トップページが読み込まれた後で、songs APIエンドポイントは繰り返し呼び出され続ける。
Even if the user is doing nothing, the songs API endpoint continues to be called repeatedly after the home page is loaded.

バックグラウンドで気づかないうちにダウンロード帯域幅はどんどん増加している。
The download bandwidth is slowly increasing in the background unnoticed.

![songs](https://user-images.githubusercontent.com/108554718/176977373-65164d32-2070-4062-ad34-dc0149758d1f.png)

1回しか呼ばれないはず？
Should it be only called once?

**Comment by cma2819** [comment]
ご報告ありがとうございます！こちらでも状況確認できました。

非常に悪質なバグになってしまっているので、修正いたします！
